spring:
  application:
    name: Ecommerce-Backend
  datasource:
    username: postgres
    password: 26111994
    url: jdbc:postgresql://localhost:5432/eCommerceDb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: TRACE

    



